[workspace]
name = "metilene3"
channels = ["bioconda", "conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "==3.10.0"
pandas = "*"
numpy = "*"
matplotlib = "*"
pandarallel = "*"
scikit-learn = "*"
seaborn = "*"
biopython = "*"
gseapy = "*"
r-base = "*"
bioconductor-chipseeker = "*"
bioconductor-org.hs.eg.db = "*"
bioconductor-txdb.hsapiens.ucsc.hg19.knowngene = "*"
bioconductor-txdb.hsapiens.ucsc.hg38.knowngene = "*"
make = "*"
c-compiler = "*"

[tasks]
build = "make"
test = "python metilene3.py -test True -o demo_output"
